### PR TITLE
clarify RepBase as a directory

### PR DESCRIPTION
**Pull request by luzengAdelaide**
@kortschak @dadelson Can you please help me to take a look and merge it?
Many thanks,
Lu

### CODE REVIEW

**Comment by kortschak** [comment]
Is this based on a report? I don't see the need for this, though the `/home/a.../` should be replaced with `~/`.

**Comment by luzengAdelaide** [comment]
@kortschak Yes, it's for the report. I should change the /home/a.../ with ~/. Should we close this merge, and open a new branch to change?

**Comment by kortschak** [comment]
What was the complaint? I don't understand.

**Comment by luzengAdelaide** [comment]
The issue is the name of "RepBase20.04.fasta" in Java code may cause confusing. It's a directory that stores Repbase libraries, rather a fasta sequence, so I'm thinking to make it more clearer.

**Comment by kortschak** [comment]
OK, but has someone actually had that confusion and filed an issue offline (obviously not here)?

The current text is `/home/aXXXXXX/RepBase20.04.fasta/*rep.ref` which makes it clear that "RepBase20.04.fasta" is a directory (the trailing`/` gives us that).

**Comment by luzengAdelaide** [comment]
OK, you're right. So I won't change the "/home/aXXXXXX/RepBase20.04.fasta/*rep.ref", but I may clarify RepBase20.04.fasta is a directory in the brackets. Should I close this merge, and open a new branch to remove /home/aXXXXXX/?

**Comment by kortschak** [comment]
Yes, close this. Fix the hard coded paths (check elsewhere for this as well), and maybe add a note that "Repeat library files are kept in the 'RepBase20.04.fasta' directory." I don't really think it's necessary, but if it makes you feel better, add some text like that.

**Pull request closed without merging**
