### PR TITLE
add repbase library

### PR DESCRIPTION
**Pull request by luzengAdelaide**
I have add the most recent RepBase library in our carp-documentation, please have a look!

### CODE REVIEW

**Comment by luzengAdelaide** [comment]
@dadelson @kortschak I've added the most recent version of Repbase in our carp-document repository, can anyone help me to "Rebase and merge" or can I do that by myself if there is no conflicts.
Thank you!

**Comment by kortschak** [comment]
We can't do this. Girinst, for better or worse, require a log in for downloads and there is a license arrangement between them and the user (us in this case). Note that I think the license is abusive, but it is what it is.

> Repbase, also known as Repbase Update, is a Database of Repetitive DNA published by Genetic Information Research Institute. You may download the content of the Database free of charge under the following conditions:
>You agree NOT to make the Repbase (or any part thereof, including Repbase Reports, Repeat Maps and other derived materials, modified or not) available to anyone outside your research group. "Make available" includes leaving the data where it may be accessible to outside individuals without your direct knowledge (e.g. on a computer to which people outside your group have login privileges), as well as directly providing it to someone. Refer any requests for the Database to GIRI (http://www.girinst.org).
>You agree NOT to use the Repbase for commercially restricted sequencing and/or proprietary sequence analysis. Commercially restricted sequencing is defined as sequencing for which a company retains patenting or licensing rights regarding the sequence, or the right to restrict or delay dissemination of the sequence; with the sole exception that sequencing is not considered to be commercially restricted if it is federally funded and the investigators adopt the data release policies endorsed at the Wellcome Trust-sponsored Bermuda meeting, i.e. immediate release of data as it is generated).
>If you are doing commercially restricted sequencing or other proprietary activities involving any portion of Repbase see the instructions at the top of this page.
>1. You agree to properly cite the Database and its specific, original contributions if directly related to your work (see References for details).
>2. You certify that you are authorized to accept this agreement on behalf of your institution.
>3. All members of your group with access to the Database agree to the same conditions. 
>By registering, you hereby agree to all of the above.

In addition to that ethico-legal issue, this is a huge file to commit.

I would prefer that a link to the download be provided rather than the file.

**Comment by luzengAdelaide** [comment]
Sure, I agree with you! Should I just delete this branch instead?

**Comment by kortschak** [comment]
Yes, please.

**Pull request closed without merging**
